### ISSUE TITLE
If the filter returns nothing LPT always shows listing

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#14]
And there is no way to get back after that even if the filter is changed to the option with data: it shows listing again.

**Comment by nikitaeverywhere** [comment]
Please provide an example link. Thanks!

**Comment by evshvarov** [comment]
![buglpt](https://user-images.githubusercontent.com/2781759/37568157-66072fda-2ae2-11e8-9511-7dde2ed2cf6a.gif)

**Comment by evshvarov** [comment]
Take any dash with LPT with filter, which can return empty results. turn on this filter, see the listing and you never come back to pivot view, only listing.

**Comment by nikitaeverywhere** [comment]
MDX before applying filter: `SELECT {[Measures].[Units Sold],[Measures].[Amount Sold]} ON 0,NON EMPTY {[Product].[P1].[Product Category].Members,%LABEL([Product].[All Product],"All Products","")} ON 1 FROM [HOLEFOODS]`
MDX after applying filter: `SELECT {[Measures].[Units Sold],[Measures].[Amount Sold]} ON 0,NON EMPTY {[Product].[P1].[Product Category].Members,%LABEL([Product].[All Product],"All Products","")} ON 1 FROM [HOLEFOODS] %FILTER %OR({[DateOfSale].[Actual].[YearSold].&[NOW] })`
MDX after applying first filter again: `DRILLTHROUGH SELECT FROM [HOLEFOODS]`

Hence LPT displays listing. Must not be an issue in LPT as:

![image](https://user-images.githubusercontent.com/4989256/37568334-724e1a5c-2adc-11e8-9009-d27ee72c51b3.png)

`changeBasicMDX` is triggered by DSW and changes MDX to `DRILLTHROUGH`. I am closing this issue here and will open one in DSW.

**Comment by nikitaeverywhere** [comment]
My apologies for focusing on the issue which is not primarily described here. Fixed with 8d5c573b00bc55aa62e1678907f75813e5da1854. Fix available in v1.8.13.
